version: '3.8'
services:
  cosmetic_recognition:
    build: ./app
    image: cosmetic_recognition
    container_name: cosmetic_recognition
    volumes:
      - ./products:/app/products
    command: /bin/bash -c "source /opt/intel/openvino/bin/setupvars.sh; python3 main.py"
    restart: on-failure
    ports:
      - "8080:8080"
